dist: trusty
sudo: false

addons:
  apt:
    packages:
      - google-chrome-stable

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3
  
script: ng test --watch false --code-coverage
after_script: "npm install coveralls && cat ./coverage/coverage.lcov | coveralls"
